@baseUrl = http://localhost:3333

# @name authenticate
POST {{baseUrl}}/integrations/auth/login
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123456"
}

> {%
    client.global.set("authToken", response.body.access_token);
%}

###

# @name register
POST {{baseUrl}}/integrations/auth/register
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@teste.com",
  "password": "123456"
}

###

# @name crete payable
POST {{baseUrl}}/integrations/payable
Content-Type: application/json
Authorization: Bearer {{authToken}}
