services:
  postgres:
    container_name: nest-pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:docker@postgres:5432/nest?schema=public"
    volumes:
      - .:/app